### PR TITLE
Fix dependency name and add it's maven url so it can be resolved.

### PR DESCRIPTION
**Pull request by chemouna**

### CODE REVIEW

**Comment by livotov** [comment]
It is published to jcenter, so you don't need to add bintray url. Or jcenter did not work for you ?

**Comment by chemouna** [comment]
with jcenter alone gradle didn't find it.

**Comment by livotov** [comment]
Please check again - just tried on a new project and it finds it perfectly just with jcenter()
Probably was a caching issue at your side at that moment and the project was not yet completely visible on jcentrer

**Comment by livotov** [comment]
compile ('eu.livotov.labs.android:CAMView:2.0.0@aar') {transitive=true}

**Pull request closed without merging**
