### PR TITLE
Make library work on Chrome 75+ & 3-D Secure v2 support

### PR DESCRIPTION
**Pull request by sandyscoffable**
Summary of changes:
 * Ditched everything related to stacked mode. I honestly don't know or understand what this is, but it makes the code a lot harder to read. I'm not using it either, whatever it is.
 * Updated to Android X, plus updated SDK versions
 * Now processing HTML in different threads (improves performance)
 * Ditched unused urlReturned variable
 * Threw away debugMode variable and functionality (a test mode to avoid
   SSL). I view this sort of code as a smell that will burn me, eventually.

I really wanted to go further with this and refactor some of the nested instantiations into their own classes, however there is cross class variable use that I'd have to manage, and I think this is enough for now.

I've tested this on Chrome versions 75, 76 (Beta) and 69 (a version that I had kicking around on an emulator)

One final footnote ... in the callbacks I'm wrapping the code with `runOnUiThread`, as at this point I want the UI thread to take over again. It may be unnecessary, but I viewed it as a safety measure
```kotlin
d3s_view.setAuthorizationListener(object : D3SSViewAuthorizationListener {

            override fun onAuthorizationCompleted(md: String, paRes: String) {
                activity?.runOnUiThread { /* My code */ }
            }

            override fun onAuthorizationStarted(view: D3SView) {
                activity?.runOnUiThread { /* My code */ }
            }

            override fun onAuthorizationWebPageLoadingProgressChanged(progress: Int) {
                activity?.runOnUiThread { /* My code */ }
            }

            override fun onAuthorizationWebPageLoadingError(errorCode: Int, description: String, failingUrl: String) {
                activity?.runOnUiThread { /* My code */ }
            }
        })
```

# Update 3rd September 2019

This now also includes changes for PDS2 (3-D Secure v2). I've been a bit ruthless and ditched `D3SDialog`, since I've had to change the interface and was faced with the choice - update or delete (and as I'm not using it I had no easy way of testing it, hence delete won).

Hope this helps someone.

### CODE REVIEW

**Comment by rihantvx** [comment]
@sandyscoffable I tested this with my app on chrome 75 and it works !!! The lib wasn't working before on chrome 75

**Comment by sandyscoffable** [comment]
> @sandyscoffable I tested this with my app on chrome 75 and it works !!! The lib wasn't working before on chrome 75

I'm at 5% rollout at the moment and monitoring for issues. I've tested with a number of providers and seems to work fine. I'm fairly paranoid though.

**Comment by 9arret** [comment]
Hi @sandyscoffable @livotov  

Could you please provide approximately date when it will be merged ? 

Thanks

**Comment by sandyscoffable** [comment]
I don't have the power to merge I'm afraid ✊

**Comment by sandyscoffable** [comment]
Ten transactions now using this branch ... all seemed to work.

**Comment by rihantvx** [comment]
@sandyscoffable Have you tried this with Android 9?

**Comment by livotov** [comment]
Hi guys, thanks for your great work. I'll try to check and merge this coming weekend!

**Comment by sandyscoffable** [comment]
> @sandyscoffable Have you tried this with Android 9?

Yeah works fine.

**Comment by sandyscoffable** [comment]
I'm now making some custom changes that are only valid for our my use case, so I'm closing this PR. Feel free to use what's here.

**Comment by mezpahlan** [comment]
I've integrated these changes and tested it locally and so far so good. Works great. It actually solves a pretty nasty performance issue with the regexes in the main library that causes high drop out rates in our users. (Basically the webview becomes super unresponsive and it appears as if you cannot click anything so are unable to complete the journey).

@livotov would you be able to look again at these changes and see if you can integrate them into the main library. The 3DSv2 support would be really helpful too.

**Pull request merged**
